# Generated by Django 3.2.12 on 2022-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('title', models.CharField(help_text='테스트 제목입니다.', max_length=20, verbose_name='테스트 제목')),
                ('description', models.CharField(blank=True, help_text='테스트 설명입니다.', max_length=64, verbose_name='테스트 설명')),
                ('author', models.CharField(help_text='테스트 제작자를 나타냅니다.', max_length=10, verbose_name='테스트 제작자')),
            ],
            options={
                'verbose_name': '테스트',
                'verbose_name_plural': '테스트(들)',
                'ordering': ['created_at'],
            },
        ),
    ]
